#!/usr/bin/env python3
"""
BID Trust - unit economics calculator.

Reads the assumption CSVs in this directory and regenerates OUTPUT.md.

    python3 models/unit_economics.py

Every cost figure in the assumption files is a PLACEHOLDER until real provider
quotations are obtained. The point of this script is that when a quotation
arrives you edit one cell in assumptions_check_costs.csv, re-run, and every
downstream number moves with it.

No third-party dependencies. Python 3.8+.
"""

import csv
import os
import sys
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))


def load_checks():
    checks = OrderedDict()
    with open(os.path.join(HERE, "assumptions_check_costs.csv"), newline="") as f:
        for row in csv.DictReader(f):
            row["provider_cost_inr"] = float(row["provider_cost_inr"])
            row["internal_cost_inr"] = float(row["internal_cost_inr"])
            row["failure_retry_rate"] = float(row["failure_retry_rate"])
            checks[row["check_code"]] = row
    return checks


def load_packages():
    packages = []
    with open(os.path.join(HERE, "assumptions_packages.csv"), newline="") as f:
        for row in csv.DictReader(f):
            row["list_price_inr"] = float(row["list_price_inr"])
            row["checks"] = [c for c in row["checks"].split(";") if c]
            packages.append(row)
    return packages


def load_globals():
    g = {}
    with open(os.path.join(HERE, "assumptions_global.csv"), newline="") as f:
        for row in csv.DictReader(f):
            g[row["key"]] = float(row["value"])
    return g


def cost_package(pkg, checks, g, reuse_rate=0.0):
    """Cost a package. reuse_rate is the share of checks served from cache
    at zero provider cost (internal cost still applies)."""
    provider = 0.0
    internal = 0.0
    missing = []
    for code in pkg["checks"]:
        c = checks.get(code)
        if c is None:
            missing.append(code)
            continue
        # A failed or retried check still costs money but yields no result.
        effective_provider = c["provider_cost_inr"] * (1.0 + c["failure_retry_rate"])
        provider += effective_provider * (1.0 - reuse_rate)
        internal += c["internal_cost_inr"]

    revenue = pkg["list_price_inr"]
    infra = g["infra_cost_per_verification"]
    support = g["support_cost_per_verification"]
    ops = g["ops_review_cost_per_verification"]
    pg = revenue * g["payment_gateway_rate"]

    total_cost = provider + internal + infra + support + ops + pg
    contribution = revenue - total_cost
    margin = contribution / revenue if revenue else 0.0

    return {
        "revenue": revenue,
        "provider": provider,
        "internal": internal,
        "infra": infra,
        "support": support,
        "ops": ops,
        "pg": pg,
        "total_cost": total_cost,
        "contribution": contribution,
        "margin": margin,
        "n_checks": len(pkg["checks"]),
        "missing": missing,
    }


def inr(x):
    return "{:,.2f}".format(x)


def pct(x):
    return "{:.1f}%".format(x * 100)


def main():
    checks = load_checks()
    packages = load_packages()
    g = load_globals()

    reuse_y1 = g["reuse_rate_year_1"]
    reuse_y3 = g["reuse_rate_year_3"]
    target = g["target_gross_margin"]

    out = []
    w = out.append

    w("# Unit Economics — Generated Output")
    w("")
    w("> **Generated by `models/unit_economics.py` from the assumption CSVs in this")
    w("> directory. Do not edit this file by hand — edit the assumptions and re-run.**")
    w("")
    w("> ### ⚠ Every provider cost below is a PLACEHOLDER.")
    w("> No figure here reflects a real quotation. These numbers exist to make the")
    w("> *structure* of the economics visible and to be replaced cell by cell as")
    w("> actual provider pricing is obtained. Do not use them for pricing decisions,")
    w("> fundraising materials, or customer commitments.")
    w("")

    w("## 1. Global assumptions")
    w("")
    w("| Assumption | Value |")
    w("|---|---|")
    w("| Payment gateway rate | {} |".format(pct(g["payment_gateway_rate"])))
    w("| Infrastructure cost per verification | ₹{} |".format(inr(g["infra_cost_per_verification"])))
    w("| Support cost per verification | ₹{} |".format(inr(g["support_cost_per_verification"])))
    w("| Ops / exception review per verification | ₹{} |".format(inr(g["ops_review_cost_per_verification"])))
    w("| Reuse rate — year 1 / year 3 | {} / {} |".format(pct(reuse_y1), pct(reuse_y3)))
    w("| Target blended gross margin | {} |".format(pct(target)))
    w("")

    w("## 2. Package economics — Year 1 (reuse rate {})".format(pct(reuse_y1)))
    w("")
    w("| Package | Price | Provider | Internal | Infra | Support | Ops | PG | Total cost | Contribution | Margin |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")

    y1 = {}
    for pkg in packages:
        r = cost_package(pkg, checks, g, reuse_rate=reuse_y1)
        y1[pkg["package_code"]] = r
        flag = " ⚠" if r["margin"] < target else ""
        w("| {} | ₹{} | ₹{} | ₹{} | ₹{} | ₹{} | ₹{} | ₹{} | ₹{} | ₹{} | {}{} |".format(
            pkg["package_name"], inr(r["revenue"]), inr(r["provider"]), inr(r["internal"]),
            inr(r["infra"]), inr(r["support"]), inr(r["ops"]), inr(r["pg"]),
            inr(r["total_cost"]), inr(r["contribution"]), pct(r["margin"]), flag))
    w("")
    w("⚠ = below the {} target gross margin.".format(pct(target)))
    w("")

    w("## 3. Package economics — Year 3 (reuse rate {})".format(pct(reuse_y3)))
    w("")
    w("Same prices, higher reuse. This table is the network effect expressed in rupees.")
    w("")
    w("| Package | Price | Provider cost Y1 | Provider cost Y3 | Margin Y1 | Margin Y3 | Δ margin |")
    w("|---|---:|---:|---:|---:|---:|---:|")
    for pkg in packages:
        a = y1[pkg["package_code"]]
        b = cost_package(pkg, checks, g, reuse_rate=reuse_y3)
        w("| {} | ₹{} | ₹{} | ₹{} | {} | {} | +{} pts |".format(
            pkg["package_name"], inr(a["revenue"]), inr(a["provider"]), inr(b["provider"]),
            pct(a["margin"]), pct(b["margin"]),
            "{:.1f}".format((b["margin"] - a["margin"]) * 100)))
    w("")

    w("## 4. Margin warnings")
    w("")
    below = [(p, y1[p["package_code"]]) for p in packages
             if y1[p["package_code"]]["margin"] < target]
    if not below:
        w("All packages meet the {} target margin under year-1 assumptions.".format(pct(target)))
    else:
        w("These packages fall below the {} target under year-1 assumptions:".format(pct(target)))
        w("")
        for p, r in below:
            need = r["total_cost"] / (1 - target) if target < 1 else 0
            w("- **{}** — margin {} at ₹{}. Break-even price ₹{}; "
              "price for target margin ₹{}.".format(
                  p["package_name"], pct(r["margin"]), inr(r["revenue"]),
                  inr(r["total_cost"]), inr(need)))
        w("")
        w("Options for each: raise the price, reduce package scope, negotiate provider")
        w("cost down, automate a manual check, or accept it as a loss-leader with an")
        w("explicit strategic reason recorded.")
    w("")

    w("## 5. Cost concentration")
    w("")
    w("Which checks dominate cost. Attack the top of this list first — either by")
    w("negotiation, by automation, or by making the check optional in default policies.")
    w("")
    rows = sorted(checks.values(),
                  key=lambda c: c["provider_cost_inr"] + c["internal_cost_inr"],
                  reverse=True)[:10]
    w("| Check | Source class | Provider | Internal | Failure rate | Effective total |")
    w("|---|---|---:|---:|---:|---:|")
    for c in rows:
        eff = c["provider_cost_inr"] * (1 + c["failure_retry_rate"]) + c["internal_cost_inr"]
        w("| {} | {} | ₹{} | ₹{} | {} | ₹{} |".format(
            c["check_name"], c["source_class"], inr(c["provider_cost_inr"]),
            inr(c["internal_cost_inr"]), pct(c["failure_retry_rate"]), inr(eff)))
    w("")

    w("## 6. Account payback")
    w("")
    w("Illustrative mid-market account, using the year-1 account shape from §12.12")
    w("of the revenue model.")
    w("")

    # Illustrative mid-market account mix.
    mix = [
        ("Subscription (BID Growth)", 12, 24999.0, None),
        ("Vendor verification", 120, None, "BUS_STANDARD"),
        ("Contractor workers", 150, None, "WORKER_STANDARD"),
        ("Employee BGV", 40, None, "BGV_STANDARD"),
    ]
    monitoring_entities, monitoring_price = 200, 49.0
    monitoring_cost_ratio = 0.30  # ASSUMPTION: provider+infra cost as share of monitoring revenue

    total_rev = 0.0
    total_contrib = 0.0
    w("| Line | Volume | Revenue | Contribution |")
    w("|---|---:|---:|---:|")
    for name, vol, price, pkg_code in mix:
        if pkg_code is None:
            rev = vol * price
            # ASSUMPTION: subscription carries ~85% gross margin (infra + support).
            contrib = rev * 0.85
        else:
            pkg = next(p for p in packages if p["package_code"] == pkg_code)
            r = y1[pkg["package_code"]]
            rev = vol * r["revenue"]
            contrib = vol * r["contribution"]
        total_rev += rev
        total_contrib += contrib
        w("| {} | {} | ₹{} | ₹{} |".format(name, vol, inr(rev), inr(contrib)))

    mon_rev = monitoring_entities * monitoring_price * 12
    mon_contrib = mon_rev * (1 - monitoring_cost_ratio)
    total_rev += mon_rev
    total_contrib += mon_contrib
    w("| Continuous monitoring | {} entities | ₹{} | ₹{} |".format(
        monitoring_entities, inr(mon_rev), inr(mon_contrib)))
    w("| **Total year 1** | | **₹{}** | **₹{}** |".format(inr(total_rev), inr(total_contrib)))
    w("")

    cac = g["cac_mid_market"]
    monthly_contrib = total_contrib / 12
    payback_months = cac / monthly_contrib if monthly_contrib else float("inf")
    blended_margin = total_contrib / total_rev if total_rev else 0

    w("| Metric | Value |")
    w("|---|---:|")
    w("| Year-1 revenue | ₹{} |".format(inr(total_rev)))
    w("| Year-1 gross contribution | ₹{} |".format(inr(total_contrib)))
    w("| Blended gross margin | {} |".format(pct(blended_margin)))
    w("| CAC (assumption) | ₹{} |".format(inr(cac)))
    w("| Gross-margin payback | **{:.1f} months** |".format(payback_months))
    w("")

    churn = g["monthly_churn_mid_market"]
    lifetime_months = 1 / churn if churn else 0
    ltv = monthly_contrib * lifetime_months
    w("| Metric | Value |")
    w("|---|---:|")
    w("| Monthly logo churn (assumption) | {} |".format(pct(churn)))
    w("| Implied lifetime | {:.0f} months |".format(lifetime_months))
    w("| LTV (gross contribution) | ₹{} |".format(inr(ltv)))
    w("| LTV / CAC | **{:.1f}×** |".format(ltv / cac if cac else 0))
    w("")
    w("Note: LTV here assumes flat spend with no expansion. Real accounts should")
    w("expand as vendor coverage and monitored entities grow, so this is a floor —")
    w("but it is a floor built on assumed churn, which is the least reliable input")
    w("in the model until real cohorts exist.")
    w("")

    # Integrity check
    missing = set()
    for pkg in packages:
        missing.update(y1[pkg["package_code"]]["missing"])
    if missing:
        w("## ⚠ Unresolved check codes")
        w("")
        w("These codes appear in packages but not in the cost file: {}".format(
            ", ".join(sorted(missing))))
        w("")

    w("---")
    w("")
    w("*Regenerate with `python3 models/unit_economics.py`.*")

    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "OUTPUT.md"), "w") as f:
        f.write(text)
    print(text)
    if missing:
        sys.exit(1)


if __name__ == "__main__":
    main()
